name = input("Enter a name! ")
verb = input("Enter a verb! ")
adjective = input ("Enter an adjective! ")
noun = input ("Enter a noun! ")
print("There once was a "+noun+" called "+name+". This "+noun+" called "+name+" was a very "+adjective+" fellow! They lived a happy life as a mischevious little fellow!")
print("One day, this little fella decided to" +verb+ "! After doing this, the little fella perished.")